const PITCHES = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const TYPES = [{suffix:'',type:'major',label:'大三和弦',formula:'1 · 3 · 5',steps:[0,4,7],degrees:[0,2,4]},{suffix:'m',type:'minor',label:'小三和弦',formula:'1 · ♭3 · 5',steps:[0,3,7],degrees:[0,2,4]},{suffix:'7',type:'seventh',label:'屬七和弦',formula:'1 · 3 · 5 · ♭7',steps:[0,4,7,10],degrees:[0,2,4,6]},{suffix:'maj7',type:'seventh',label:'大七和弦',formula:'1 · 3 · 5 · 7',steps:[0,4,7,11],degrees:[0,2,4,6]},{suffix:'m7',type:'seventh',label:'小七和弦',formula:'1 · ♭3 · 5 · ♭7',steps:[0,3,7,10],degrees:[0,2,4,6]},{suffix:'m7♭5',type:'seventh',label:'半減七和弦',formula:'1 · ♭3 · ♭5 · ♭7',steps:[0,3,6,10],degrees:[0,2,4,6]},{suffix:'dim',type:'other',label:'減三和弦',formula:'1 · ♭3 · ♭5',steps:[0,3,6],degrees:[0,2,4]},{suffix:'aug',type:'other',label:'增三和弦',formula:'1 · 3 · ♯5',steps:[0,4,8],degrees:[0,2,4]},{suffix:'sus2',type:'other',label:'掛二和弦',formula:'1 · 2 · 5',steps:[0,2,7],degrees:[0,1,4]},{suffix:'sus4',type:'other',label:'掛四和弦',formula:'1 · 4 · 5',steps:[0,5,7],degrees:[0,3,4]}];
const LETTERS = ['C','D','E','F','G','A','B'];
const NATURAL_PITCHES = {C:0,D:2,E:4,F:5,G:7,A:9,B:11};
function spellTone(root,degree,target){const rootLetter=LETTERS.indexOf(root[0]),letter=LETTERS[(rootLetter+degree)%7],natural=NATURAL_PITCHES[letter];let offset=(PITCHES.indexOf(target)-natural+12)%12;if(offset>6)offset-=12;const accidental=offset>0?'♯'.repeat(offset):'♭'.repeat(-offset);return `${letter}${accidental}`}
const CHORDS = PITCHES.flatMap(root => TYPES.map(def => {const notes=def.steps.map(step=>PITCHES[(PITCHES.indexOf(root)+step)%12]);return {name:`${root}${def.suffix}`,notes,displayNotes:notes.map((note,index)=>spellTone(root,def.degrees[index],note)),...def}}));
const PRESETS = [{title:'流行萬用',name:'I–V–vi–IV',degrees:[0,7,9,5],letterDegrees:[0,4,5,3],suffixes:['','','m','']},{title:'爵士回家',name:'ii–V–I',degrees:[2,7,0],letterDegrees:[1,4,0],suffixes:['m7','7','maj7']},{title:'民謠下行',name:'I–vi–IV–V',degrees:[0,9,5,7],letterDegrees:[0,5,3,4],suffixes:['','m','','']},{title:'12 小節藍調',name:'I7–IV7–V7',degrees:[0,0,0,0,5,5,0,0,7,5,0,7],letterDegrees:[0,0,0,0,3,3,0,0,4,3,0,4],suffixes:Array(12).fill('7')}];
const STRINGS = ['E','A','D','G','B','E'];
const FRET_START = 1;
const FRET_END = 22;
const OPEN_SHAPES = {C:{frets:'x 3 2 0 1 0',label:'開放和弦'},D:{frets:'x x 0 2 3 2',label:'開放和弦'},E:{frets:'0 2 2 1 0 0',label:'開放和弦'},F:{frets:'1 3 3 2 1 1',label:'六弦橫按和弦'},G:{frets:'3 2 0 0 0 3',label:'開放和弦'},A:{frets:'x 0 2 2 2 0',label:'開放和弦'},Am:{frets:'x 0 2 2 1 0',label:'開放和弦'},Dm:{frets:'x x 0 2 3 1',label:'開放和弦'},Em:{frets:'0 2 2 0 0 0',label:'開放和弦'},Cmaj7:{frets:'x 3 2 0 0 0',label:'開放和弦'},Dm7:{frets:'x x 0 2 1 1',label:'開放和弦'},Em7:{frets:'0 2 0 0 0 0',label:'開放和弦'},G7:{frets:'3 2 0 0 0 1',label:'開放和弦'},A7:{frets:'x 0 2 0 2 0',label:'開放和弦'}};
let current = CHORDS.find(c => c.name === 'Cmaj7'); let filter = 'all'; let key = 'C'; let sequence = JSON.parse(localStorage.getItem('chordcraft-progression') || 'null') || presetItems(PRESETS[1]); let audioContext; let activeNodes=[]; let schedulerTimer; let clockRunId=0; let progressionIndex=0; let subdivisionIndex=0; let nextNoteTime=0; let loopEnabled=false; let progressionPlaying=false; let metronomePlaying=false; let countInActive=false;
const byId = id => document.getElementById(id);
const RHYTHMS = {quarter:{label:'四分',subdivisions:1},eighth:{label:'八分',subdivisions:2},sixteenth:{label:'十六分',subdivisions:4},swing:{label:'Swing',subdivisions:2}};
const savedPractice = JSON.parse(localStorage.getItem('chordroom-practice') || '{}');
let pendingSettings={bpm:Number(savedPractice.bpm)||90,meter:Number(savedPractice.meter)===3?3:4,rhythm:RHYTHMS[savedPractice.rhythm]?savedPractice.rhythm:'quarter',countIn:savedPractice.countIn!==false};
let activeSettings={...pendingSettings};
function notePitchClass(noteName){const match=noteName.match(/^([A-G])([#♯♭]*)$/);if(!match)return -1;let pitch=NATURAL_PITCHES[match[1]];for(const accidental of match[2])pitch+=accidental==='♭'?-1:1;return (pitch+120)%12}
function getChord(name){const exact=CHORDS.find(chord=>chord.name===name);if(exact)return exact;const match=name.match(/^([A-G][#♯♭]*)(.*)$/);if(!match)return {name,notes:[name],displayNotes:[name],label:'和弦'};const [rootName,suffix]=match.slice(1),pitchClass=notePitchClass(rootName),definition=TYPES.find(type=>type.suffix===suffix),canonical=definition&&CHORDS.find(chord=>chord.name===`${PITCHES[pitchClass]}${suffix}`);if(!canonical)return {name,notes:[name],displayNotes:[name],label:'和弦'};return {...canonical,name,displayNotes:canonical.notes.map((note,index)=>spellTone(rootName,definition.degrees[index],note))}}
function presetItems(preset){const rootIndex=PITCHES.indexOf(key);return preset.degrees.map((degree,index)=>`${spellTone(key,preset.letterDegrees[index],PITCHES[(rootIndex+degree)%12])}${preset.suffixes[index]}`)}
function renderList(){ const term = byId('chordSearch').value.trim().toLowerCase(); const shown = CHORDS.filter(c => (filter === 'all' || c.type === filter) && (c.name.toLowerCase().includes(term) || c.notes.join(' ').toLowerCase().includes(term) || c.displayNotes.join(' ').toLowerCase().includes(term))); byId('chordCount').textContent = `${shown.length} 個`; byId('chordList').innerHTML = shown.length ? shown.map(c=>`<button class="chord-card ${c.name===current.name?'active':''}" data-chord="${c.name}"><strong>${c.name}</strong><small>${c.displayNotes.join(' · ')}</small></button>`).join('') : '<p class="sequence-empty">找不到相符和弦</p>'; }
function scaleFor(chord){const rootName=chord.displayNotes[0];if(chord.name.includes('m7♭5'))return {name:`${rootName} 洛克里亞`,steps:[0,1,3,5,6,8,10],degrees:[0,1,2,3,4,5,6]};if(chord.name.includes('dim'))return {name:`${rootName} 全－半減音階`,steps:[0,2,3,5,6,8,9,11],degrees:[0,1,2,3,4,5,5,6]};if(chord.name.includes('aug'))return {name:`${rootName} 全音音階`,steps:[0,2,4,6,8,10],degrees:[0,1,2,3,4,5]};if(chord.name.endsWith('m')||chord.name.endsWith('m7'))return {name:`${rootName} 自然小音階`,steps:[0,2,3,5,7,8,10],degrees:[0,1,2,3,4,5,6]};if(chord.name.endsWith('7')&&!chord.name.endsWith('maj7'))return {name:`${rootName} 混合利底亞`,steps:[0,2,4,5,7,9,10],degrees:[0,1,2,3,4,5,6]};return {name:`${rootName} 大音階`,steps:[0,2,4,5,7,9,11],degrees:[0,1,2,3,4,5,6]}}
function practiceTip(chord,isScale,scaleName){if(isScale)return `<b>${scaleName}</b>是相容選項之一；請依調性與和弦功能決定實際用法。`;if(chord.name.endsWith('sus2')||chord.name.endsWith('sus4'))return `<b>${chord.name}</b>：聽根音、五音與掛留音，並觀察掛留音是否解決到三音。`;if(chord.type==='seventh')return `<b>${chord.name}</b>：先定位根音，再比較三音與七音的聲部走向。`;if(chord.name.endsWith('dim'))return `<b>${chord.name}</b>：聽根音、降三度與減五度形成的緊張感。`;if(chord.name.endsWith('aug'))return `<b>${chord.name}</b>：聽根音、大三度與升五度形成的對稱張力。`;return `<b>${chord.name}</b>：根音確立中心，三音決定大小調色彩，五音提供穩定支撐。`}
function renderFretboard(){const root=current.notes[0],scaleInfo=scaleFor(current),scale=scaleInfo.steps.map(step=>PITCHES[(PITCHES.indexOf(root)+step)%12]),scaleNames=scale.map((note,index)=>spellTone(current.displayNotes[0],scaleInfo.degrees[index],note)),isScale=byId('viewMode').value==='scale',shape=shapeFor(current),activeNotes=isScale?scale:current.notes,activeNames=isScale?scaleNames:current.displayNotes;byId('selectedName').textContent=current.name;byId('noteList').textContent=current.displayNotes.join(' · ');byId('formula').textContent=current.formula;byId('scaleName').textContent=scaleInfo.name;byId('soundLabel').textContent=`${current.name} ${isScale?scaleInfo.name:'和弦'}`;byId('shapeName').textContent=OPEN_SHAPES[current.name]?.label||'四弦音高配置';byId('shapeFrets').textContent=shape;byId('insight').querySelector('p').innerHTML=practiceTip(current,isScale,scaleInfo.name);const cells=[],displayStrings=[...STRINGS].reverse();displayStrings.forEach((open,stringIndex)=>{const stringNumber=stringIndex+1,stringName=stringNumber===1?'高音 E':stringNumber===6?'低音 E':`${open} 弦`;cells.push(`<div class="string-label" aria-label="第 ${stringNumber} 弦，${stringName}"><strong>${open}</strong><small>${stringNumber}</small></div>`);for(let fret=FRET_START;fret<=FRET_END;fret++){const note=PITCHES[(PITCHES.indexOf(open)+fret)%12],active=activeNotes.includes(note),kind=note===root?'root':active?'tone':'',displayNote=active?activeNames[activeNotes.indexOf(note)]:note;cells.push(`<div class="string"><button class="note ${kind}" aria-label="第 ${stringNumber} 弦第 ${fret} 格：${displayNote}${kind==='root'?'，根音':kind?'，已選音':''}" data-note="${note}">${kind?displayNote:''}</button></div>`)}});byId('fretboardGrid').innerHTML=cells.join('')}
function renderFretLabels(){const scroll=byId('fretboard').querySelector('.fretboard-scroll'),labels=byId('fretboard').querySelector('.fret-labels');if(labels.parentElement!==scroll)scroll.append(labels);labels.innerHTML=`<span class="string-label-spacer" aria-hidden="true"></span>${Array.from({length:FRET_END-FRET_START+1},(_,index)=>`<span aria-label="第 ${index+FRET_START} 格">${index+FRET_START}</span>`).join('')}`;labels.setAttribute('aria-label','第 1 至第 22 格標示');document.querySelector('footer p').textContent='標準調弦 · 1–22 格'}
function shapeFor(chord){const open=OPEN_SHAPES[chord.name];if(open)return open.frets;const activeStrings=STRINGS.slice(2);for(let base=0;base<=11;base++){for(let shift=0;shift<chord.notes.length;shift++){const frets=activeStrings.map((openString,index)=>{let fret=(PITCHES.indexOf(chord.notes[(index+shift)%chord.notes.length])-PITCHES.indexOf(openString)+12)%12;while(fret<base)fret+=12;return fret});if(Math.max(...frets)-Math.min(...frets)<=4)return `x x ${frets.join(' ')}`}}return '無可用指型'}
function renderPresets(){byId('presets').innerHTML=PRESETS.map((p,i)=>`<button class="preset" data-preset="${i}"><small>${p.title}</small><strong>${p.name}</strong></button>`).join('')}
function renderSequence(){byId('sequence').innerHTML=sequence.length?sequence.map((name,i)=>`<div class="sequence-item"><button class="sequence-card" data-remove="${i}" title="移除 ${name}"><strong>${name}</strong><small>${getChord(name).displayNotes.join(' · ')}</small></button><span class="move-controls"><button data-move="${i},-1" aria-label="${name} 向前移">‹</button><button data-move="${i},1" aria-label="${name} 向後移">›</button></span></div>${i<sequence.length-1?'<span class="arrow">→</span>':''}`).join(''):'<p class="sequence-empty">從左側選擇一個和弦，開始建立行進。</p>'}
function choose(name){current=getChord(name); renderList();renderFretboard(); toast(`已選擇 ${name}，可加入目前行進`)}
function toast(message){const node=byId('toast');node.textContent=message;node.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>node.classList.remove('show'),2100)}
function download(){if(!sequence.length){toast('先加入至少一個和弦');return}const lines=['Chordroom｜吉他和弦行進','','和弦行進：',sequence.join(' → '),'','組成音：',...sequence.map((name,i)=>`${i+1}. ${name}: ${getChord(name).displayNotes.join(' · ')}`),'','提示：先練習各和弦的實際組成音，再觀察相鄰和弦之間距離最近的聲部連接。'];const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='chordroom-progression.txt';a.click();URL.revokeObjectURL(a.href);toast('文字檔已匯出')}
function context(){audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();return audioContext}
function trackNode(node){activeNodes.push(node);node.onended=()=>{activeNodes=activeNodes.filter(item=>item!==node)}}
function stopAudio(){activeNodes.forEach(node=>{try{node.stop()}catch{}});activeNodes=[]}
function frequency(note,octave=4){return 440*Math.pow(2,(PITCHES.indexOf(note)-9+(octave-4)*12)/12)}
function scheduleTone(note,start,duration,octave=4,volume=.12){const ctx=context(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='triangle';osc.frequency.value=frequency(note,octave);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.018);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain).connect(ctx.destination);osc.start(start);osc.stop(start+duration+.03);trackNode(osc)}
function tone(note,at=0,duration=1,octave=4){scheduleTone(note,context().currentTime+at,duration,octave)}
function scheduleClick(start,accent,isBeat){const ctx=context(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(accent?1560:isBeat?1080:760,start);gain.gain.setValueAtTime(accent?.16:isBeat?.09:.045,start);gain.gain.exponentialRampToValueAtTime(.0001,start+.045);osc.connect(gain).connect(ctx.destination);osc.start(start);osc.stop(start+.055);trackNode(osc)}
function scheduleChord(chord,start,duration){chord.notes.forEach((note,index)=>scheduleTone(note,start+index*.018,duration,index===0?3:4,.075))}
function stopClock(){clearInterval(schedulerTimer);schedulerTimer=null;subdivisionIndex=0;nextNoteTime=0;clockRunId++}
function updateTransportButtons(){byId('progressionPlayButton').textContent=progressionPlaying?'Ⅱ 暫停行進':'▶ 行進';byId('progressionPlayButton').setAttribute('aria-pressed',String(progressionPlaying));byId('metronomeButton').textContent=metronomePlaying?'■ 停止節拍器':'● 節拍器';byId('metronomeButton').setAttribute('aria-pressed',String(metronomePlaying));byId('metronomeButton').classList.toggle('active',metronomePlaying)}
function settingsText(){return `${pendingSettings.bpm} BPM · ${pendingSettings.meter}/4 · ${RHYTHMS[pendingSettings.rhythm].label}`}
function updateStatus(message=''){byId('transportStatus').textContent=message||settingsText()}
function stepDuration(index,settings){const beat=60/settings.bpm;if(settings.rhythm==='swing')return index%2===0?beat*2/3:beat/3;return beat/RHYTHMS[settings.rhythm].subdivisions}
function queueVisual(start,callback,runId=clockRunId){setTimeout(()=>{if(runId===clockRunId)callback()},Math.max(0,(start-context().currentTime)*1000))}
function finishProgression(at){queueVisual(at,()=>{progressionPlaying=false;countInActive=false;progressionIndex=0;document.querySelectorAll('.sequence-card').forEach(card=>card.classList.remove('playing'));updateTransportButtons();updateStatus('行進完成 · '+settingsText());if(!metronomePlaying)stopClock()})}
function advanceStep(start){const subdivisions=RHYTHMS[activeSettings.rhythm].subdivisions,total=activeSettings.meter*subdivisions;nextNoteTime+=stepDuration(subdivisionIndex,activeSettings);subdivisionIndex++;if(subdivisionIndex<total)return;subdivisionIndex=0;activeSettings={...pendingSettings};if(countInActive){countInActive=false;progressionIndex=0;return}if(!progressionPlaying)return;progressionIndex++;if(progressionIndex<sequence.length)return;if(loopEnabled){progressionIndex=0;return}finishProgression(nextNoteTime);progressionPlaying=false}
function scheduleStep(){const subdivisions=RHYTHMS[activeSettings.rhythm].subdivisions,isBeat=subdivisionIndex%subdivisions===0,isAccent=subdivisionIndex===0,start=nextNoteTime,visualSubdivision=subdivisionIndex,visualProgressionIndex=progressionIndex,visualSettings={...activeSettings},wasCountIn=countInActive,wasProgression=progressionPlaying;const chordName=sequence[visualProgressionIndex];scheduleClick(start,isAccent,isBeat);if(wasProgression&&!wasCountIn&&chordName){const duration=Math.max(.07,Math.min(.52,stepDuration(subdivisionIndex,activeSettings)*.68));scheduleChord(getChord(chordName),start,duration)}queueVisual(start,()=>{byId('metronomeButton').classList.add('pulse');setTimeout(()=>byId('metronomeButton').classList.remove('pulse'),70);if(wasCountIn){updateStatus(`預備拍 ${Math.floor(visualSubdivision/subdivisions)+1} / ${visualSettings.meter}`);return}if(wasProgression&&chordName){document.querySelectorAll('.sequence-card').forEach((card,index)=>card.classList.toggle('playing',index===visualProgressionIndex));updateStatus(`第 ${visualProgressionIndex+1} 顆 ${chordName} · ${visualSettings.bpm} BPM · ${visualSettings.meter}/4 · ${RHYTHMS[visualSettings.rhythm].label}`)}});advanceStep(start)}
function scheduler(){const ctx=context();while((progressionPlaying||metronomePlaying)&&nextNoteTime<ctx.currentTime+.1)scheduleStep()}
function startClock(){stopAudio();stopClock();activeSettings={...pendingSettings};nextNoteTime=context().currentTime+.07;subdivisionIndex=0;scheduler();schedulerTimer=setInterval(scheduler,25)}
function stopProgression(reset=true){progressionPlaying=false;countInActive=false;clockRunId++;if(reset)progressionIndex=0;document.querySelectorAll('.sequence-card').forEach(card=>card.classList.remove('playing'));if(!metronomePlaying){stopClock();stopAudio()}updateTransportButtons();updateStatus(reset?'已停止 · '+settingsText():'已暫停 · '+settingsText())}
function playProgression(){if(progressionPlaying){stopProgression();return}if(!sequence.length){toast('先加入至少一個和弦');return}const keepMetronome=metronomePlaying;stopClock();stopAudio();metronomePlaying=keepMetronome;progressionPlaying=true;progressionIndex=0;countInActive=pendingSettings.countIn;updateTransportButtons();updateStatus(countInActive?'預備拍準備中':'行進準備中');startClock()}
function toggleMetronome(){metronomePlaying=!metronomePlaying;if(metronomePlaying&&!progressionPlaying)startClock();else if(!metronomePlaying&&!progressionPlaying){stopClock();stopAudio();updateStatus()}updateTransportButtons()}
function stopPracticeForPreview(){progressionPlaying=false;metronomePlaying=false;countInActive=false;stopClock();stopAudio();updateTransportButtons();document.querySelectorAll('.sequence-card').forEach(card=>card.classList.remove('playing'))}
function playChord(chord=current,duration=1.45){stopPracticeForPreview();const button=byId('playButton');button.classList.add('playing');button.setAttribute('aria-pressed','true');chord.notes.forEach((note,index)=>tone(note,index*.025,duration,index===0?3:4));clearTimeout(window.chordButtonTimer);window.chordButtonTimer=setTimeout(()=>{button.classList.remove('playing');button.setAttribute('aria-pressed','false')},duration*1000);toast(`${chord.name} 正在發聲`)}
function playScale(){stopPracticeForPreview();const info=scaleFor(current),notes=[...info.steps.map(step=>PITCHES[(PITCHES.indexOf(current.notes[0])+step)%12]),current.notes[0]];notes.forEach((note,index)=>tone(note,index*.3,.28,index===notes.length-1?5:4));toast(`${info.name} 上行`)}
byId('chordSearch').addEventListener('input',renderList);byId('filters').addEventListener('click',e=>{const button=e.target.closest('[data-filter]');if(!button)return;filter=button.dataset.filter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===button));renderList()});byId('chordList').addEventListener('click',e=>{const button=e.target.closest('[data-chord]');if(button)choose(button.dataset.chord)});byId('addButton').addEventListener('click',()=>{if(progressionPlaying)stopProgression();sequence.push(current.name);renderSequence();toast(`${current.name} 已加入目前行進`)});byId('viewMode').addEventListener('change',renderFretboard);byId('keySelect').addEventListener('change',e=>{if(progressionPlaying)stopProgression();key=e.target.value;toast(`已切換至 ${key} 調，選擇預設即可套用轉調`)});byId('presets').addEventListener('click',e=>{const button=e.target.closest('[data-preset]');if(!button)return;if(progressionPlaying)stopProgression();sequence=presetItems(PRESETS[button.dataset.preset]);document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b===button));renderSequence();toast('已載入常見和弦行進')});byId('sequence').addEventListener('click',e=>{if(progressionPlaying)stopProgression();const move=e.target.closest('[data-move]');if(move){const [index,delta]=move.dataset.move.split(',').map(Number),target=index+delta;if(target<0||target>=sequence.length)return;[sequence[index],sequence[target]]=[sequence[target],sequence[index]];renderSequence();toast('和弦順序已調整');return}const button=e.target.closest('[data-remove]');if(!button)return;const [removed]=sequence.splice(Number(button.dataset.remove),1);renderSequence();toast(`已移除 ${removed}`)});byId('saveButton').addEventListener('click',()=>{localStorage.setItem('chordcraft-progression',JSON.stringify(sequence));toast('行進與練習設定已儲存')});byId('exportButton').addEventListener('click',download);byId('keySelect').innerHTML=PITCHES.map(note=>`<option value="${note}">${note}</option>`).join('');
function applyGuitarTheme(theme){const isAcoustic=theme==='acoustic';byId('fretboardGrid').classList.toggle('acoustic',isAcoustic);byId('fretboardGrid').setAttribute('aria-label',`${isAcoustic?'木吉他':'電吉他'}指板`);localStorage.setItem('chordroom-guitar-theme',theme);toast(`已切換為${isAcoustic?'木吉他':'電吉他'}配色`)}
const savedGuitarTheme=localStorage.getItem('chordroom-guitar-theme')==='acoustic'?'acoustic':'electric';byId('guitarTheme').value=savedGuitarTheme;byId('fretboardGrid').classList.toggle('acoustic',savedGuitarTheme==='acoustic');byId('fretboardGrid').setAttribute('aria-label',`${savedGuitarTheme==='acoustic'?'木吉他':'電吉他'}指板`);byId('guitarTheme').addEventListener('change',e=>applyGuitarTheme(e.target.value));
function applyTheme(preference,announce=false){const media=matchMedia('(prefers-color-scheme: dark)'),resolved=preference==='system'?(media.matches?'dark':'light'):preference;document.documentElement.dataset.theme=resolved;document.querySelector('meta[name="theme-color"]').content=resolved==='dark'?'#0b1020':'#f6f8fc';byId('themeSelect').value=preference;localStorage.setItem('chordroom-theme',preference);if(announce)toast(`已切換為${preference==='system'?'跟隨系統':preference==='dark'?'深色':'淺色'}主題`)}
const themeMedia=matchMedia('(prefers-color-scheme: dark)'),savedTheme=['system','light','dark'].includes(localStorage.getItem('chordroom-theme'))?localStorage.getItem('chordroom-theme'):'system';applyTheme(savedTheme);byId('themeSelect').addEventListener('change',e=>applyTheme(e.target.value,true));themeMedia.addEventListener('change',()=>{if(byId('themeSelect').value==='system')applyTheme('system')});
function clampTempo(value){return Math.min(240,Math.max(40,Number(value)||90))}
function savePracticeSettings(){localStorage.setItem('chordroom-practice',JSON.stringify(pendingSettings))}
function changePracticeSettings(){pendingSettings={bpm:clampTempo(byId('tempoInput').value),meter:Number(byId('meterSelect').value),rhythm:byId('rhythmSelect').value,countIn:byId('countInToggle').checked};byId('tempoInput').value=pendingSettings.bpm;byId('tempoRange').value=pendingSettings.bpm;savePracticeSettings();if(!progressionPlaying&&!metronomePlaying){activeSettings={...pendingSettings};updateStatus()}else toast('新設定將於下一小節套用')}
byId('tempoInput').value=pendingSettings.bpm;byId('tempoRange').value=pendingSettings.bpm;byId('meterSelect').value=String(pendingSettings.meter);byId('rhythmSelect').value=pendingSettings.rhythm;byId('countInToggle').checked=pendingSettings.countIn;
byId('tempoRange').addEventListener('input',e=>{byId('tempoInput').value=e.target.value;changePracticeSettings()});byId('tempoInput').addEventListener('change',changePracticeSettings);byId('meterSelect').addEventListener('change',changePracticeSettings);byId('rhythmSelect').addEventListener('change',changePracticeSettings);byId('countInToggle').addEventListener('change',changePracticeSettings);
renderList();renderFretboard();renderFretLabels();renderPresets();renderSequence();updateTransportButtons();updateStatus();
byId('playButton').addEventListener('click',()=>playChord());byId('scalePlayButton').addEventListener('click',playScale);byId('progressionPlayButton').addEventListener('click',playProgression);byId('metronomeButton').addEventListener('click',toggleMetronome);byId('loopButton').addEventListener('click',()=>{loopEnabled=!loopEnabled;byId('loopButton').classList.toggle('active',loopEnabled);byId('loopButton').setAttribute('aria-pressed',String(loopEnabled));toast(loopEnabled?'重複播放已開啟':'重複播放已關閉')});
